export const GET_ALL_NETWORK_REQUEST_SUCCESS = "GET_ALL_NETWORK_REQUEST_SUCCESS";
export const GET_ALL_NETWORK_REQUEST_FAILURE = "GET_ALL_NETWORK_REQUEST_FAILURE";
export const GET_ALL_NETWORK_REQUEST_PENDING = "GET_ALL_NETWORK_REQUEST_PENDING";